#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

# --------------------------------------------------------
# configure prompt
# ----------------------------------------------------------
if [ "$PS1" ]; then
	if [ "`id -u`" -eq 0 ]; then
		export PS1='hydra#>'
	else
		export PS1='hydra$>'
	fi
fi

export PAGER='/bin/more'
export EDITOR='/bin/vi'

# -----------------------------------------------------
# Source configuration files from /etc/profile.d
# -------------------------------------------------------
for i in /etc/profile.d/*.sh ; do
	if [ -r "$i" ]; then
		. $i
	fi
done
unset i


# -------------------------------------------------------
# Wifi configure
# ------------------------------------------------------
#echo "interface wlan0" > /etc/dhcpcd.conf
#echo "  static ip_address=192.168.2.1/24" >> /etc/dhcpcd.conf
#echo "  nohook wpa_supplicant" >> /etc/dhcpcd.conf

#service dhcpd restart

# -------------------------------------------------------
# DHCP (dnsmasq) configure
# ------------------------------------------------------
#echo "interface=wlan0" > /etc/dnsmasq.conf
#echo "  dhcp-range=192.168.2.2,192.168.2.5,255.255.255.0,24h" >> /etc/dnsmasq.conf

# -------------------------------------------------------
# Hostapd configure
# ------------------------------------------------------
#echo "interface=wlan0" > /etc/hostapd/hostapd.conf
#echo "driver=nl80211" >> /etc/hostapd/hostapd.conf
#echo "ssid=hydraak" >> /etc/hostapd/hostapd.conf
#echo "hw_mode=g" >> /etc/hostapd/hostapd.conf
#echo "channel=" >> /etc/hostapd/hostapd.conf
#echo "wmm_enabled=0" >> /etc/hostapd/hostapd.conf
#echo "macaddr_acl=0" >> /etc/hostapd/hostapd.conf
#echo "auth_algs=1" >> /etc/hostapd/hostapd.conf
#echo "ignore_broadcast_ssid=0" >> /etc/hostapd/hostapd.conf
#echo "wpa=2" >> /etc/hostapd/hostapd.conf
#echo "wpa_passphrase=1234598765" >> /etc/hostapd/hostapd.conf
#echo "wpa_key_mgmt=WPA-PSK" >> /etc/hostapd/hostapd.conf
#echo "wpa_pairwise=TKIP" >> /etc/hostapd/hostapd.conf
#echo "rsn_pairwise=CCMP" >> /etc/hostapd/hostapd.conf

#sed -i 's/#DAEMON_CONF="/etc/hostapd/hostapd.conf"/DAEMON_CONF="/etc/hostapd/hostapd.conf"/' /etc/default/hostapd

# ---------------------------------------------------------
# Add IP Tables
# ----------------------------------------------------------

# iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

# iptables-restore < /etc/iptables.ipv4.nat

# iptables-restore < /etc/iptables.ipv4.nat

# ---------------------------------------------------------
# Aliases
# ---------------------------------------------------------
alias cls=clear
alias ll="ls -lah"
alias md=mkdir

# --------------------------------------------------------
# Set Date
# --------------------------------------------------------
date -s '2019-3-3 11:59:59'

